#!/usr/bin/env bash
# Script to install nginx on the remote server
# Installing nginx
apt-get -y update
apt-get -y install nginx

echo "Hello World!" > /var/www/html/index.nginx-debian.html

service nginx restart
