#!/usr/bin/env bash

sudo echo "Ceci n'est pas une page" > /var/www/html/404.html

# Create an Nginx configuration file for the custom error page
sudo echo 'server {
    listen 80;
    server_name philstech.tech;

    error_page 404 /404.html;

    location = /404.html {
        root /var/www/html;
    }

}' > /etc/nginx/sites-available/custom_404.conf
# Enable the custom error page configuration
sudo ln -s /etc/nginx/sites-available/custom_404.conf /etc/nginx/sites-enabled/

# Test Nginx configuration and reload
sudo nginx -t && /usr/sbin/nginx -s reload
