#!/usr/bin/env bash
# Script to reconfigure not found page

sudo echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html > /dev/null

# Create an Nginx configuration file for the custom error page
cat <<EOL > /etc/nginx/sites-available/custom_404
server {
    listen 80 default_server;
    server_name _;

    location / {
        root /var/www/html;
        try_files /custom_404.html =404;
    }

    error_page 404 /custom_404.html;
    location = /custom_404.html {
        root /var/www/html;
    }
}
EOL

# Enable the custom 404 page configuration
if [ ! -e /etc/nginx/sites-enabled/custom_404 ]; then
    sudo ln -s /etc/nginx/sites-available/custom_404 /etc/nginx/sites-enabled/
fi

# Test Nginx configuration and reload
sudo nginx -t && sudo service nginx reload

# Clean up temporary files
sudo rm /etc/nginx/sites-available/custom_404
