#!/usr/bin/env bash
# Script that installs and configures  HAproxy in a load balancer 
apt-get -y install --no-install-recommends software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.0
apt-get -y update
apt-get -y install haproxy=2.0.\*
echo -e "\nfrontend http\n\tbind *:80\n\tmode http\n\tdefault_backend web-backend\n\nbackend web-backend\n\tbalance roundrobin\n\tserver 299248-web-01 54.196.42.35:80 check\n\tserver 299248-web-02 34.229.56.179:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg
service haproxy restart
