#!/usr/bin/env bash
#Displaying text using while, if, elif statements
a=1
while [ $a -le 10 ]
do
	echo "Best School"
	if [ $a -eq 4 ]
	then
		echo "bad luck"
	elif [ $a -eq 8 ]
	then
		echo "good luck"
	fi
	((a++))
done
